### PR TITLE
generate test data

### PR DESCRIPTION
**Pull request by kevinhughes27**
Here is a decent set of generated data from the latest android build.

cc @wingleungchan

### CODE REVIEW

**Comment by wingleungchan** [comment]
Looks like the issue with the homeRoster = awayRoster still exists.

**Comment by kevinhughes27** [comment]
Oh woops I totally forgot to fix that issue! 

I'm pretty sure it doesn't affect the stats calculation but we should still fix the data. A quick copy pasta from [here](http://parity-server.herokuapp.com/teams) should do it

**Comment by wingleungchan** [comment]
I tried to push the changes back to the repository, but am getting a 403. Do you need to allow me write permissions?

**Comment by kevinhughes27** [comment]
invite resent

**Comment by wingleungchan** [comment]
Having some trouble interpreting some data:
For catch_d.json - I see a throwaway, a d-block, but the person with the d-block also scored the point. Would that not be a callahan?

For drop.json - I see a drop, but then the next pass is made by the same team. A player on the other team should have picked up the disc.

**Comment by wingleungchan** [comment]
In mini_game.json - the first 3 points are repeated. I presume it is just a copy paste issue and will remove the duplicates. For the last point, the team the offense and defense teams were switched (based on who scored the previous point) which cannot happen unless there is a pull but that is not the case.

**Comment by patrickkenzie** [comment]
> For the last point, the team the offense and defense teams were switched (based on who scored the previous point) which cannot happen unless there is a pull but that is not the case.

Right now the android app doesn't prevent teams from starting with possession immediately after they score, which might explain how this data was generated. It's on the issue list now!

**Comment by kevinhughes27** [comment]
catch_d and d produce the same events it just looks different in the UI and lets the stats keeper push less buttons. The data looks fine to me until the DEFENSE and POINT right in a row. I am going to re-record a catch_d example to make sure that is what I entered in the android app.

In drop.json Jaime boss and Morgan Howard are on different teams. This data looks correct to me.

That is super weird in mini_game.json The score looks right though so somehow the android app is duplicating the point.

As far as the teams being wrong @patrickkenzie is right that was probably just my mistake. The android app used to enforce the switch back and forth but as I was separating some concerns I removed it to simplify some of the logic. I figured its easy enough for the stats keeper to do this right (or undo) that we didn't need to enforce it.

**Comment by wingleungchan** [comment]
Mini_game2 also has a duplicate point. I can remove that manually as well. 

For turnovers.json, the last 2 events look weird - It is a drop immediately followed by a point. Another callahan? (ie: throw, receiver gacks it, defender catches for callahan)

**Comment by wingleungchan** [comment]
@kevinhughes27 I am still getting a 403 when trying to do a git push. Error is:
Remote: Permission to kevinhughes27/parity-server.git denied to wingleungchan

**Comment by kevinhughes27** [comment]
You haven't accepted the invite yet according to github. You could also try forking the repo, pushing there and then opening the pull request.

**Comment by wingleungchan** [comment]
Aha - that was it. Weird, I thought I had accepted. Not a very useful error message from github IMHO.

For drop.json, you are correct. Morgan and Jaime are on different teams. In this situation, what should be the result? I see a DROP and a THREW_DROP being charged to the same person. I believe there are 3 different scenarios right?
DROP - 100% charged to receiver
THROWAWAY - 100% charged to thrower
THROWDROP - 50% charged to receiver, 50% to thrower
... and that is independent of defense if they are involved

**Comment by kevinhughes27** [comment]
If the same person got the Drop and the Threw drop that sounds like a bug in the calculation. If you push the test suite I'll be able to look at it.

**Pull request merged**
