### PR TITLE
New event model parser

### PR DESCRIPTION
**Pull request by kevinhughes27**
This is my WIP on consuming stats output by the `BookKeeper`.

I wrote this ~2 weeks ago and I don't really recall exactly where its at. I seem to remember its mostly working except for pick-ups (which is a pretty lame stat). There is some subtlety around the pull etc that makes this harder than it sounds.

A good next thing would be to remove the pick-up stat and see if everything else matches. I have a pretty solid test harness that tests bigger and bigger pieces until it tries to match the whole game. This makes it easier to track down problems.

@agodding - you can see some of the data oddities I've ran into by looking at the json files in the diff. Have a look through the parser code as well since I think there is some cross over of logic between what you had to do in order to write out events and what I have to do to turn them into stats.

cc @patrickkenzie

### CODE REVIEW

**Comment by kevinhughes27** [comment]
Note to me:

I've been using the npm `json` module cli for debugging the parser. E.g. if the stats don't match after 5 points of game 2 this is what I run:

```
cat db/week02_game2.json | json points | json 5
```

* Pipe the contents of the file to JSON
* extract the points sub-key and pipe that to another json call
* access the desired array index

**Comment by kevinhughes27** [comment]
I did some work on this today. There is 3 bugs currently in the data produced by the `Bookkeeper`. Two of them can be fixed automatically the 3rd could be but not in a way that plays nice with my current test setup.

* **PASS events that are missing a firstActor**. I can detect these and fix them. I have seen two cases, a matching secondActor and a secondActor that doesn't make sense. I reconcile with the previous event and delete the malformed pass event. This seems to work and matches the old stat string results.

* **O and D player lists are flipped** - I can detect this by looking at the first event and fix if need be. We should fix in the Android app and then remove this hack

* **Duplicate points**. It seems pretty common that a point is fully duplicated in the new model. This can be detected and removed but I made it raise instead. My test harness assumes the same number of points in each so I need to delete the points in the local json as I find them to be able to keep using this code.

**Comment by kevinhughes27** [comment]
Okay fixed the issue with the test suite and now we can just log the duplicate points without manually editing them. I am going to have a look at the android code later today.

**Comment by agodding** [comment]
@kevinhughes27 a fix for the oddities between new/old data is [on its way!](https://github.com/kevinhughes27/parity-client/tree/fix-undo-operation)

Basically, the undo operation is super tricky to predict. In some cases it deletes the last event and retains the first actor. In other cases it clears the first actor, etc. I'm in the process of writing some unit tests for all the different types of undo operations that can occur then I'll PR the work.

**Comment by kevinhughes27** [comment]
I figured undo was a bit hairy. Thinks will be a lot simpler to iterate on after we can confidently switch over. 

Slight tangent - would it be possible to do some kind of integration test of the android app easily? I have a decent list of all the stats in my test suite but it would be cool to port here and write tests that press out the button sequence required for each stat.

**Pull request closed without merging**
